create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  image_url text not null,
  storage_path text not null,
  guest_name text not null,
  created_at timestamptz not null default now()
);

alter table public.photos enable row level security;

create policy "Anyone can view wedding photos"
on public.photos for select
to anon
using (true);

create policy "Guests can add wedding photos"
on public.photos for insert
to anon
with check (true);

insert into storage.buckets (id, name, public)
values ('wedding-photos', 'wedding-photos', true)
on conflict (id) do nothing;

create policy "Anyone can view wedding photo files"
on storage.objects for select
to anon
using (bucket_id = 'wedding-photos');

create policy "Guests can upload wedding photo files"
on storage.objects for insert
to anon
with check (bucket_id = 'wedding-photos');
